name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: publish
      run: |
        cd TypeInfoApp
        dotnet publish -c release
      
    - name: Change base-tag in index.html from / to the necessary
      run: sed -i 's/<base href="\/" \/>/<base href="\/TypeInfo\/" \/>/g' ./TypeInfoApp/bin/release/net5.0/publish/wwwroot/index.html
      
    - name: Add .nojekyll file
      run: touch ./TypeInfoApp/bin/release/net5.0/publish/wwwroot/.nojekyll
      
    - uses: maxheld83/ghpages@master
      name: gh-pages publish
      env:
        BUILD_DIR: ./TypeInfoApp/bin/release/net5.0/publish/wwwroot
        GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
