name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: publish
      run: |
        cd TypeInfoApp
        dotnet publish -c release
      
    - uses: maxheld83/ghpages@master
      name: gh-pages publish
      env:
        BUILD_DIR: ./randomtestpathblabla
        GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
